@RunningGroupAPI_HostAddress = http://localhost:5076

POST {{RunningGroupAPI_HostAddress}}/api/Authentication/login
Content-Type: application/json

{
    "email": "new.user@gmail.com",
    "password": "Newuser@123"
}
###
